alias ls='exa --group-directories-first --icons=auto --color=auto --no-quotes --classify=auto'
alias ff='fastfetch'
alias cat='bat'
alias grep='rg'
alias edit='micro'
alias calc='gnome-calculator &'
alias xorw='echo "$WAYLAND_DISPLAY $XDG_SESSION_TYPE"'
alias mud='~/Documents/personal/mud/mud.sh'
